export const cars = [
  {
    VinNumber: '1HGBH41JXMN109186',
    name: 'Toyota Camry',
    owner: 'John Doe',
    phoneNumber: '555-555-555',
    infoFromClient: 'Client prefers red color',
    additionalInfo: 'Well-maintained, low mileage',
    date: '23-10-2023',
  },
  {
    VinNumber: '2HGFC2F59JH520434',
    name: 'Honda Civic',
    owner: 'Jane Smith',
    phoneNumber: '555-5678',
    infoFromClient: 'Client wants automatic transmission',
    additionalInfo: 'Fuel-efficient, great for city driving',
    date: '24-10-2023',
  },
  {
    VinNumber: '1FAFP4041KF131509',
    name: 'Ford Mustang',
    owner: 'Michael Johnson',
    phoneNumber: '555-9012',
    infoFromClient: 'Client is looking for a sporty model',
    additionalInfo: 'Powerful engine, sleek design',
    date: '25-10-2023',
  },
  {
    VinNumber: '1G1YY32G915120062',
    name: 'Chevrolet Corvette',
    owner: 'Emily Davis',
    phoneNumber: '555-3456',
    infoFromClient: 'Client needs extra trunk space',
    additionalInfo: 'Sporty, high-performance vehicle',
    date: '26-10-2023',
  },
  {
    VinNumber: '5UXWX9C53H0W58752',
    name: 'BMW X5',
    owner: 'David Brown',
    phoneNumber: '555-7890',
    infoFromClient: 'Client prefers luxury features',
    additionalInfo: 'Premium materials, advanced technology',
    date: '27-10-2023',
  },
  {
    VinNumber: 'JTHGL46F595025883',
    name: 'Lexus LS',
    owner: 'Sarah Wilson',
    phoneNumber: '555-2345',
    infoFromClient: 'Client wants a comfortable ride',
    additionalInfo: 'Luxury sedan, smooth handling',
    date: '28-10-2023',
  },
];
