export const cars = [
  {
    id: 1,
    name: 'Toyota Camry',
    owner: 'John Doe',
    phoneNumber: '555-1234',
    infoFromClient: 'Client prefers red color',
    additionalInfo: 'Well-maintained, low mileage',
    date: '23-10-2023',
  },
  {
    id: 2,
    name: 'Honda Civic',
    owner: 'Jane Smith',
    phoneNumber: '555-5678',
    infoFromClient: 'Client wants automatic transmission',
    additionalInfo: 'Fuel-efficient, great for city driving',
    date: '24-10-2023',
  },
  {
    id: 3,
    name: 'Ford Mustang',
    owner: 'Michael Johnson',
    phoneNumber: '555-9012',
    infoFromClient: 'Client is looking for a sporty model',
    additionalInfo: 'Powerful engine, sleek design',
    date: '25-10-2023',
  },
  {
    id: 4,
    name: 'Chevrolet Cruze',
    owner: 'Emily Davis',
    phoneNumber: '555-3456',
    infoFromClient: 'Client needs extra trunk space',
    additionalInfo: 'Compact yet spacious interior',
    date: '26-10-2023',
  },
  {
    id: 5,
    name: 'BMW 3 Series',
    owner: 'David Brown',
    phoneNumber: '555-7890',
    infoFromClient: 'Client prefers luxury features',
    additionalInfo: 'Premium materials, advanced technology',
    date: '27-10-2023',
  },
  {
    id: 6,
    name: 'Mercedes-Benz E-Class',
    owner: 'Sarah Wilson',
    phoneNumber: '555-2345',
    infoFromClient: 'Client wants a comfortable ride',
    additionalInfo: 'Plush interior, smooth handling',
    date: '28-10-2023',
  },
  {
    id: 7,
    name: 'Audi A4',
    owner: 'Michael Taylor',
    phoneNumber: '555-6789',
    infoFromClient: 'Client seeks performance and style',
    additionalInfo: 'Dynamic driving experience, elegant design',
    date: '29-10-2023',
  },
  {
    id: 8,
    name: 'Nissan Altima',
    owner: 'Jessica Martinez',
    phoneNumber: '555-0123',
    infoFromClient: 'Client needs a reliable daily driver',
    additionalInfo: 'Dependable, spacious interior',
    date: '30-10-2023',
  },
  {
    id: 9,
    name: 'Volkswagen Jetta',
    owner: 'Daniel Anderson',
    phoneNumber: '555-4567',
    infoFromClient: 'Client wants a fuel-efficient sedan',
    additionalInfo: 'Economical, comfortable ride',
    date: '31-10-2023',
  },
  {
    id: 10,
    name: 'Subaru Impreza',
    owner: 'Jennifer Garcia',
    phoneNumber: '555-8901',
    infoFromClient: 'Client prefers all-wheel drive',
    additionalInfo: 'Great handling, reliable performance',
    date: '01-11-2023',
  },
];
