const inputFields = [
  {
    label: 'Imię',
    name: 'clientFirstName',
    maxLength: 40,
    minLength: 1,
    required: true,
  },
  {
    label: 'Nazwisko',
    name: 'clientLastName',
    maxLength: 40,
    minLength: 1,
    required: true,
  },
  {
    label: 'Numer telefonu',
    name: 'phone',
    type: 'tel',
    maxLength: 15,
    minLength: 9,
    required: true,
  },
  {
    label: 'E-mail właściciela',
    name: 'email',
    type: 'email',
    maxLength: 40,
    minLength: 6,
    required: true,
  },
  {
    label: 'Marka',
    name: 'brand',
    maxLength: 40,
    minLength: 1,
    required: true,
  },
  {
    label: 'Model',
    name: 'model',
    maxLength: 40,
    minLength: 1,
    required: true,
  },
  {
    label: 'Numer VIN',
    name: 'vinNumber',
    maxLength: 17,
    minLength: 17,
    required: true,
  },
  {
    label: 'Silnik',
    name: 'engine',
    maxLength: 50,
    minLength: 1,
    required: false,
  },
  {
    label: 'Numer rejestracyjny',
    name: 'registrationNumber',
    maxLength: 11,
    minLength: 6,
    required: true,
  },
  {
    label: 'Informacje od mechanika',
    name: 'mechanicInfo',
    required: false,
  },
  {
    label: 'Informacje od klienta',
    name: 'clientInfo',
    required: false,
  },
  {
    label: 'Data produkcji',
    name: 'productionDate',
    type: 'text',
    required: false,
  },
  { label: 'Przebieg', name: 'mileage', required: false },
  {
    label: 'Data przyjęcia',
    name: 'dateOfArrival',
    type: 'date',
    required: true,
  },
  {
    label: 'Data deadline',
    name: 'deadlineDate',
    type: 'date',
    required: true,
  },
];

export default inputFields;
